### ISSUE TITLE
Trouble adding sequence to scaffold strand 

### ISSUE THREAD

**Issue by Prateek1410** [douglaslab/cadnano2#11]
When adding the seq on the 5' end, no sequence appears along the 3' strand for some distance. So, my sequence file has a lot of question marks. Although, adding another break and thus, another seq to fill this 'empty' part of scaffold strand did help generate an atomic structure but the structure was hollowed along that 'empty' region indicating that Cando didn't consider the seq I had added on the second occasion.

**Comment by sdouglas** [comment]
These are likely issues with the design, not bugs in cadnano2. I would carefully watch the [tutorials](http://cadnano.org/docs.html) and, if possible, find an experienced user to help walk you through these steps. It seems likely that your scaffold is discontinuous and you'll need to join it all together before you can export sequences properly. Unfortunately the GUI does not provide much hint about this state or how to fix it, but it's something that we can consider improving in the future.
