### ISSUE TITLE
Sequence not added throughout the structure

### ISSUE THREAD

**Issue by Prateek1410** [douglaslab/cadnano2#12]
Upon using the add sequence tool, the sequence is found missing in certain parts of the nanostructure. I have tried with each of the sequences provided but to no avail.

**Comment by sdouglas** [comment]
The most likely cause is that your scaffold is not continuous and you are missing some crossovers somewhere. You can confirm this by using the Paint Tool and changing the scaffold color (first click on the blue color box and use the color picker to choose something else). Continuous regions of the scaffold will be colored the same.
