### ISSUE TITLE
Cadnano crashes when using "autostaple" function

### ISSUE THREAD

**Issue by Simone-dotcom** [douglaslab/cadnano2#13]
Traceback (most recent call last):
  File "C:\Users\Rosa Anna\Downloads\cadnano2\.\views\pathview\strand\stranditem.py", line 166, in strandHasNewOligoSlot
    self._xover3pEnd._updateColor(strand)
  File "C:\Users\Rosa Anna\Downloads\cadnano2\.\views\pathview\strand\xoveritem.py", line 458, in _updateColor
    vhi5 = self._node5.virtualHelixItem()
AttributeError: 'NoneType' object has no attribute 'virtualHelixItem'

**Comment by sdouglas** [comment]
Thanks for reporting this issue. Can you send me your source file so I can investigate? In the meantime, one solution is to save your file before the crash and then perform autostaple in the [old version of cadnano](http://cadnano.org/legacy).

**Comment by Simone-dotcom** [comment]
Yes of course, here there are two files. Thank you a lot.

Il giorno ven 18 giu 2021 alle ore 18:30 Shawn Douglas <
***@***.***> ha scritto:

**Comment by sdouglas** [comment]
You'll need to send me a separate email outside of the github issue tracker. Your response only posted a new comment at https://github.com/douglaslab/cadnano2/issues/13 but did not attach the files.

**Comment by sdouglas** [comment]
Please try using latest cadnano2 release. If you still experience problems, please send the source files so we can test further.
