### ISSUE TITLE
pencil tool: 3' end drag

### ISSUE THREAD

**Issue by revyakinlab** [douglaslab/cadnano2#15]
Hi Douglas lab folks --

I am not certain if what I was trying to do was legit, but this behavior has reproduced 3 times. In the pencil tool when one clicks and drags a scaffold 3' end the program crashes with the following message. I was trying to join to broken ends of the scaffold

C:\Users\ostap bender\Documents\GitHub\cadnano2>python main.py
Plugin loaded, has access to cadnano: <module 'cadnano' from '.\\cadnano.py'>
Traceback (most recent call last):
  File ".\views\pathview\strand\endpointitem.py", line 195, in mousePressEvent
    getattr(self, toolMethodName)(modifiers, event, self.idx())
  File ".\views\pathview\strand\endpointitem.py", line 314, in pencilToolMousePress
    tempXover.updateBase(vhi, mStrand, idx)
  File ".\views\pathview\tools\penciltool.py", line 624, in updateBase
    self._node5.updateForFloatFromStrand(virtualHelixItem, strand5p, idx)
  File ".\views\pathview\tools\penciltool.py", line 360, in updateForFloatFromStrand
    self.updatePositionAndAppearance()
  File ".\views\pathview\tools\penciltool.py", line 535, in updatePositionAndAppearance
    self._updateLabel(isLeft)
  File ".\views\pathview\tools\penciltool.py", line 462, in _updateLabel
    num = self._partnerVirtualHelix.number()
  File ".\views\pathview\virtualhelixitem.py", line 132, in number
    return self._modelVirtualHelix.number()
AttributeError: 'NoneType' object has no attribute 'number'

Cheers! 
Andrey Revyakin

**Comment by sdouglas** [comment]
When a 5' and 3' endpoint are adjacent on the same helix, you should be able to use the **Select** tool and shift+click on either endpoint to join them into a single strand. The Pencil tool is generally used to force non-standard connections between distant strands.

I'm not able to reproduce this bug at the moment. If you still have issues, please share the source .json file and more detail, for example a screenshot, so I know exactly what edit you are attempting to make.

**Comment by revyakinlab** [comment]
Thanks, Shawn! I was able to work around this and got the structure done. I probably should have described the behavior more accurately (my student experienced it, too).

---
AR mobile +44 (0)772 921 8315
if calling from outside the UK, omit (0)

________________________________
