### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by chalmers4c** [douglaslab/cadnano2#18]
Hello

I am wondering where are the plugins? Like autobreak. I installed the cadnano2 package through into virtual server following the mac doc.

**Comment by sdouglas** [comment]
Hi, thanks for reporting this issue. I’ll investigate and try to fix this in the next few days.

**Comment by sdouglas** [comment]
In general you will get very poor folding results if you use autobreak, as it was built before we had any solid understanding of what determines folding accuracy. For now, I recommend breaking manually using heuristics defined in https://www.nature.com/articles/ncomms2095 - specifically “rule 3”. Our original algorithm does not do this optimization.

**Comment by sdouglas** [comment]
Update: I've decided to permanently remove the autobreak button from cadnano2. It does not provide optimal staple output. We hope to release an improved autobreak tool in the near future, but for now I would break manually following the heuristics referenced in my previous comment.
