### ISSUE TITLE
Save does not work.

### ISSUE THREAD

**Issue by xiongqc** [douglaslab/cadnano2#2]
The "save" function throws an error, although "save as" works without any of the write permission issues:
![save](https://user-images.githubusercontent.com/6223216/50308343-f1b82d80-0468-11e9-8a47-cf6b3307caa0.PNG)
Using latest github version 2.3.0
![version](https://user-images.githubusercontent.com/6223216/50308396-13b1b000-0469-11e9-8ef0-375587af6177.PNG)

**Comment by sdouglas** [comment]
Unable to reproduce. Please download the latest release and let me know if you continue to experience this issue.
