### ISSUE TITLE
pip is not recognized in step 5 (windows OS)

### ISSUE THREAD

**Issue by indranil40693** [douglaslab/cadnano2#22]
'pip' is not recognized as an internal or external command,
operable program or batch file.

How to resolve this?

**Comment by sdouglas** [comment]
This sounds like a issue specific to your computer configuration, not a cadnano2 issue. I recommend or finding someone with experience to help you (or searching online for tutorials). You'll need to install python3, and make sure that your environment is configured so the python folder (which includes pip) is in your PATH. I believe the installer offers an option to configure the path for you, so re-installing with that enabled may help.
