### ISSUE TITLE
cadnano2 doesn't start after installation according to the manual 

### ISSUE THREAD

**Issue by DGRY1** [douglaslab/cadnano2#23]
C:\Users\rvlhu\OneDrive\Documents\GitHub\cadnano2>python main.py
python: can't open file 'C:\\Users\\rvlhu\\OneDrive\\Documents\\GitHub\\cadnano2\\main.py': [Errno 2] No such file or directory

C:\Users\rvlhu\OneDrive\Documents\GitHub\cadnano2>python cadnano2\main.py
Traceback (most recent call last):
  File "C:\Users\rvlhu\OneDrive\Documents\GitHub\cadnano2\cadnano2\main.py", line 13, in <module>
    from . import cadnano
ImportError: attempted relative import with no known parent package

**Comment by sdouglas** [comment]
The old instructions no longer work. Try using the command `cadnano2` per the new README instructions.

**Comment by havefunanita** [comment]
> C:\Users\rvlhu\OneDrive\Documents\GitHub\cadnano2>python main.py python: can't open file 'C:\Users\rvlhu\OneDrive\Documents\GitHub\cadnano2\main.py': [Errno 2] No such file or directory
> 
> C:\Users\rvlhu\OneDrive\Documents\GitHub\cadnano2>python cadnano2\main.py Traceback (most recent call last): File "C:\Users\rvlhu\OneDrive\Documents\GitHub\cadnano2\cadnano2\main.py", line 13, in from . import cadnano ImportError: attempted relative import with no known parent package

Hello, there. May I ask...have you been fixed your problem? I have met the same problem. Unfortunately, this is my first time using Python, and I really don't know anything about this....o(╥﹏╥)o

**Comment by XinRenL** [comment]
attempted relative import with no known parent package
i can't too.Is this i don't why

**Comment by XinRenL** [comment]
The issue has been resolved and I need to add SSI authentication when I download PyQt6. After a successful installation, you can start by referring to README.

**Comment by sdouglas** [comment]
Great. Please file a new issue if problems persist.
