### ISSUE TITLE
Windows user unable to upgrade to 2.4.4

### ISSUE THREAD

**Issue by chenxiang-lin** [douglaslab/cadnano2#24]
I cannot seem to upgrade to 2.4.4 on Windows. Despite downloading the latest build and following the instructions in README, I am stuck on 2.4.3 (without the drag-and-drop function and missing the Break Tool icon). 

(cn24x) C:\Windows\System32>pip install cadnano2
Collecting cadnano2
  Using cached **cadnano2-2.4.3-py3-none-any.whl** (644 kB)
Collecting PyQt6
  Using cached PyQt6-6.2.3-cp36-abi3-win_amd64.whl (6.2 MB)
Collecting PyQt6-sip<14,>=13.2
  Using cached PyQt6_sip-13.2.1-cp39-cp39-win_amd64.whl (71 kB)
Collecting PyQt6-Qt6>=6.2.3
  Using cached PyQt6_Qt6-6.2.3-py3-none-win_amd64.whl (44.3 MB)
Installing collected packages: PyQt6-sip, PyQt6-Qt6, PyQt6, cadnano2
Successfully installed PyQt6-6.2.3 PyQt6-Qt6-6.2.3 PyQt6-sip-13.2.1 **cadnano2-2.4.3**

**Comment by sdouglas** [comment]
What happens when you try this command (within the active virtual env)?
`pip install --upgrade cadnano2`

**Comment by chenxiang-lin** [comment]
(cn24x) C:\Windows\System32>pip3 install --upgrade cadnano2
Requirement already satisfied: cadnano2 in c:\virtualenvs\cn24x\lib\site-packages (2.4.3)
Requirement already satisfied: PyQt6 in c:\virtualenvs\cn24x\lib\site-packages (from cadnano2) (6.2.3)
Requirement already satisfied: PyQt6-sip<14,>=13.2 in c:\virtualenvs\cn24x\lib\site-packages (from PyQt6->cadnano2) (13.2.1)
Requirement already satisfied: PyQt6-Qt6>=6.2.3 in c:\virtualenvs\cn24x\lib\site-packages (from PyQt6->cadnano2) (6.2.3)

**Comment by sdouglas** [comment]
Oops, I neglected to upload the new build to [pypi](https://pypi.org/project/cadnano2/) (only up to 2.4.3 was available). I've done that, so the same upgrade command should work now. 

For future reference, you can also force pip to install directly from a git repo, for example:
```pip install git+https://github.com/douglaslab/cadnano2.git```
