### ISSUE TITLE
main.py file is unable to execute

### ISSUE THREAD

**Issue by saurabhumrao** [douglaslab/cadnano2#26]
C:\Python310\python.exe: can't open file 'C:\\Users\\Saurabh\\Documents\\GitHub\\cadnano2\\main.py': [Errno 2] No such file or directory

details:
C:\Users\Saurabh\Documents\GitHub\cadnano2>dir
 Volume in drive C is OS
 Volume Serial Number is 8A2A-F7F4

 Directory of C:\Users\Saurabh\Documents\GitHub\cadnano2

05/01/2022  08:26 PM    <DIR>          .
05/01/2022  08:26 PM    <DIR>          ..
05/01/2022  08:26 PM                56 .gitignore
05/01/2022  08:26 PM    <DIR>          cadnano2
05/01/2022  08:26 PM             1,518 CHANGELOG.md
05/01/2022  08:26 PM    <DIR>          dist
05/01/2022  08:26 PM             1,215 LICENSE
05/01/2022  08:26 PM                93 pyproject.toml
05/01/2022  08:26 PM             3,676 README.md
05/01/2022  08:26 PM               973 setup.py
               6 File(s)          7,531 bytes
               4 Dir(s)  68,517,232,640 bytes free

C:\Users\Saurabh\Documents\GitHub\cadnano2>python main.py
python: can't open file 'C:\\Users\\Saurabh\\Documents\\GitHub\\cadnano2\\main.py': [Errno 2] No such file or directory

C:\Users\Saurabh\Documents\GitHub\cadnano2>pyqt5
'pyqt5' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Saurabh\Documents\GitHub\cadnano2>pip install PyQt5
Requirement already satisfied: PyQt5 in c:\python310\lib\site-packages (5.15.6)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\python310\lib\site-packages (from PyQt5) (12.10.1)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in c:\python310\lib\site-packages (from PyQt5) (5.15.2)

C:\Users\Saurabh\Documents\GitHub\cadnano2>pip install networkx
Requirement already satisfied: networkx in c:\python310\lib\site-packages (2.8)

C:\Users\Saurabh\Documents\GitHub\cadnano2>python main.py
python: can't open file 'C:\\Users\\Saurabh\\Documents\\GitHub\\cadnano2\\main.py': [Errno 2] No such file or directory

C:\Users\Saurabh\Documents\GitHub\cadnano2>py main.py
C:\Python310\python.exe: can't open file 'C:\\Users\\Saurabh\\Documents\\GitHub\\cadnano2\\main.py': [Errno 2] No such file or directory

**Comment by sdouglas** [comment]
Recent updates have change the way cadnano2 is installed and run. We no longer invoke main.py. Please try using the latest instructions on the main [project page](https://github.com/douglaslab/cadnano2).
