### ISSUE TITLE
install cadnano2.2 on windows

### ISSUE THREAD

**Issue by LifengOSU** [douglaslab/cadnano2#27]
\Documents\GitHub\cadnano2\cadnano2>python main.py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from . import cadnano
ImportError: cannot import name 'cadnano' from '__main__' (main.py)

_Any solutions? Thanks!_

**Comment by sdouglas** [comment]
The command for launching cadnano has changed. Please refer to the README documentation for the correct approach.
