### ISSUE TITLE
error: No module named 'ui' when a warning dialog box is called

### ISSUE THREAD

**Issue by Dan-X** [douglaslab/cadnano2#28]
The error appears when exporting a design with an error (for example staple loops in my case). 
full error message: 
```
Traceback (most recent call last):
  File "/Users/[username]/opt/anaconda3/envs/cadnano/lib/python3.6/site-packages/cadnano2/controllers/documentcontroller.py", line 425, in actionExportStaplesSlot
    from ui.dialogs.ui_warning import Ui_Warning
ModuleNotFoundError: No module named 'ui'
zsh: abort      cadnano2
```
commenting out this part in `documentcontroller.py` will bypass the problem.

I suppose this part of the code is to call a warning dialogue box, but somehow the ./ui module cannot be found.  

system: macOS 12.5.1
cadnano2                  2.4.4
pyqt6                     6.2.3
pyqt6-qt6                 6.2.3
pyqt6-sip                 13.2.1
python                    3.6.13

same issue on another PC with python 3.10, same installed cadnano2 via pip.

**Comment by elija-feigl** [comment]
The issue occurs if you have circular staples in your design, which is likely unintended.
The associated Warning-Window appears to be broken, causing the crash.
