### ISSUE TITLE
ModuleNotFound Error in actionExportStaplesSlot

### ISSUE THREAD

**Issue by erdabravest2001** [douglaslab/cadnano2#31]
Hi there,
Sorry to bother you but I am still having this issue. Although #29 , "fixed" it. I am still getting this issue when exporting my staples. My staples and scaffold are supposed to be looped as I am designing a circular ring structure.
![image](https://user-images.githubusercontent.com/61441923/197372940-714cb92a-f5fa-444f-9b15-a71efda84e68.png)

Regards,

**Comment by sdouglas** [comment]
I’ve pushed a new version to pypi that includes the patch, try updating and see if it works.
