### ISSUE TITLE
codnano2 launching problem

### ISSUE THREAD

**Issue by Prateek525** [douglaslab/cadnano2#32]
I am not able to launch  codnano2 using terminal window, it is showing that "no such file or directory" .

**Comment by sdouglas** [comment]
Please provide the terminal output so we can help diagnose the issue.

**Comment by nano292** [comment]
![image](https://user-images.githubusercontent.com/42695961/205488478-cc6a0d34-a678-4e19-a18f-cfba6a4f5733.png)

**Comment by sdouglas** [comment]
The latest version is run using the `cadnano2` command, please see the [readme](https://github.com/douglaslab/cadnano2#running).

**Comment by Wei19931025** [comment]
![WeChat Image_20230222141459](https://user-images.githubusercontent.com/123926613/220528776-d7156c3f-cbca-46a7-be68-29f9ab89d1ca.png)
I'm sorry, I'm not sure how to launch it.
