### ISSUE TITLE
Reproducible Crush Bug

### ISSUE THREAD

**Issue by sakaiy-dna** [douglaslab/cadnano2#34]
Dear Shawn,

I'm training my left-hander colleague who uses opposite click button configuration, and I found cadnano2 always crushes when the user tries to move mouse with right button holding on path panel, with ctrl key (attempting to pan the panel and holding opposite mouse button by mistake). It's great if you consider to fix this bug in next update.

System: Windows 10
Cadnano version: 2.4.7

Yusuke

**Comment by sdouglas** [comment]
Thanks for reporting this. The latest version (v2.4.10) should address this issue, but please let me know if it doesn't. If you do see additional crashes, it would be helpful if you include the terminal output.
