### ISSUE TITLE
Crush Bug when save as but cancel

### ISSUE THREAD

**Issue by VpOthello** [douglaslab/cadnano2#35]
![cadnano_bug](https://user-images.githubusercontent.com/31194654/207487789-857ab169-fdc3-4b84-9c5d-ff8c4ff0a83e.png)

System version: windows 11 22H2 22621.819
Cadnano version: 2.4.8

It's great if you consider to fix this bug in next update.

Thanks for your contribution.

**Comment by sdouglas** [comment]
Thanks for reporting this. We'll update it to `Qt.WindowType.Dialog` for PyQt6 compatibility.
