### ISSUE TITLE
There are some problems with implementing 3D with Maya

### ISSUE THREAD

**Issue by Yuxixi-Li** [douglaslab/cadnano2#36]
Is the latest version of Cadnano2 still only available for Maya2015? I tried to load the plugin in Maya 2015 following the tutorial from 2018, but I didn't get it loaded successfully

**Comment by sdouglas** [comment]
Hi, unfortunately Maya is no longer supported:

https://forums.autodesk.com/t5/maya-forum/cadnano-plug-in-in-maya-2016/m-p/8497122/highlight/true#M67478
