### ISSUE TITLE
MacOS Monterey error installing CaDNAno2

### ISSUE THREAD

**Issue by divita** [douglaslab/cadnano2#37]
Hellos!
I am trying to install CaDNAno2 using the Terminal-directed instructions on the website. I am on step 5 and am running into an error (attached screenshot shows the error). My computer is a macOS Monterey 12.3 with that pretentious M1 Max chip that seems to hate everything sometimes. Any help would be great!
Thanks!
![Screen Shot 2022-12-28 at 2 58 58 PM](https://user-images.githubusercontent.com/1069274/209866253-2606f145-87ed-4dc3-852d-b2296a26594c.png)

Divita

**Comment by sdouglas** [comment]
Are you using the system Python or have you installed the Homebrew version (per the readme)? In the latter case I’d try upgrading Python, it looks like you’re on version 3.8 and PyQt6-sip is failing to install.

**Comment by sdouglas** [comment]
If you continue having problems, feel free to reopen this issue.
