### ISSUE TITLE
when trying to run cadnano2 it says no 

### ISSUE THREAD

**Issue by BioPhys-PhD** [douglaslab/cadnano2#38]

**Comment by BioPhys-PhD** [comment]
after installing according to the template when i use python main.py 
it says "python: can't open file 'C:\\Users\\zakdo\\Documents\\GitHub\\cadnano2\\main.py': [Errno 2] No such file or directory"

**Comment by BioPhys-PhD** [comment]
fixed it nevermind thank you!

**Comment by Wei19931025** [comment]
I have encountered the same problem, how to solve it?
