### ISSUE TITLE
Issue in installation of Cadnano

### ISSUE THREAD

**Issue by SunSummoner** [douglaslab/cadnano2#39]
![Capture](https://user-images.githubusercontent.com/95202116/221112031-4c9a10b7-4fdc-4359-bb67-7a3f2c994c81.JPG)
I got this after following the installation steps.

**Comment by sdouglas** [comment]
Hi, the program no longer launches via main.py. The [README](https://github.com/douglaslab/cadnano2#running) specifies the new method.

**Comment by SunSummoner** [comment]
> Hi, the program no longer launches via main.py. The [README](https://github.com/douglaslab/cadnano2#running) specifies the new method.

Ok, thank you so much.
