### ISSUE TITLE
Can't clone the repository again

### ISSUE THREAD

**Issue by Kairos05** [douglaslab/cadnano2#41]
Had some trouble with cadnano2, the command python main.py is not working, can anyone indicate me what I might have done wrong? Thank you!

**Comment by sdouglas** [comment]
This is very unlikely to be a cadnano issue. It sounds like a git issue — I recommend researching how to clone a repository online, for example in the GitHub documentation. 

Incidentally, we have removed main.py and now rely on a new command to launch cadnano2. If you check out the README you can find the latest documentation, including how to `pip install` the software.
