### ISSUE TITLE
caDNAno2 on windows does not save edits

### ISSUE THREAD

**Issue by sdey15** [douglaslab/cadnano2#5]
I edited the staples meanually and when I was almost about to be done on an m13 origami, I noticed that no changes were saved. I remember I continuously hit "ctrl+s" and the save button. Moreover, I tried saving manually by "save as" function as well. That does not work as well. Not to mention, without saving it is almost impossible to work. Please help. 

Your sincerely,
Swarup Dey

**Comment by Prateek1410** [comment]
Hey! I have the same issue. Does the file name at the top left corner change to 'C'?

**Comment by sdouglas** [comment]
Let me know if you continue to experience similar behavior in the latest release (2.4.x).
