### ISSUE TITLE
Unable to install cadnano2

### ISSUE THREAD

**Issue by Markopppp** [douglaslab/cadnano2#50]
Hello,

 I have followed the installation instructions on Windows 10 domain computers but I always end up with the same problem

C:\Users\USER\cadnano2\cadnano2>python main.py
Traceback (most recent call last):
  File "C:\Users\USER\cadnano2\cadnano2\main.py", line 13, in <module>
    from . import cadnano
ImportError: attempted relative import with no known parent package

Python is installed to c:\. What can be the cause of this problem?

Best regards
Marko

**Comment by sdouglas** [comment]
Please confirm that you are following the README instructions for running the application. It does not use main.py anymore.
