### ISSUE TITLE
cadnano2 not opening after installation

### ISSUE THREAD

**Issue by akkrox** [douglaslab/cadnano2#52]
Read and replicated the exact readme instructions, tried running the cadnano2 command and while cmd opens for a split second it closes immediately after. Not sure if I'm on an incorrect path.
![image](https://github.com/douglaslab/cadnano2/assets/148269792/f01802e3-ae20-49d5-9271-f111ac9ae05a)

**Comment by sdouglas** [comment]
Hmm. It seems setuptools is missing from your environment.

Try running `pip install setuptools` and let me know if that helps.

**Comment by akkrox** [comment]
installing setuptools fixed the previous error, but this error pops up:
![image](https://github.com/douglaslab/cadnano2/assets/148269792/403fcd6e-7acb-40f2-8cfa-ad49998f0e93)

**Comment by sdouglas** [comment]
I recommend that you try to `pip install` that one and any other missing dependencies. It seems the installation failed to do so automatically.

**Comment by akkrox** [comment]
is there a specific list of dependencies that are supposed to come with the installation? I followed the readthedocs (including upgrading pyqt to 6) and the same error pops up

**Comment by akkrox** [comment]
Update: may have figured it out. Will post instructions if successful

**Comment by sdouglas** [comment]
Typically you can find the requirements in setup.py, but since it’s hard to tell what you’re missing you might just have to check one at a time. It shouldn’t be more than 4 or 5 packages total. Note this was only tested in Python 3.10 so it’s possible that 3.12 breaks some things that previously worked fine.

**Comment by akkrox** [comment]
Downgrading python to 3.10.0 worked: turns out the imp module was deprecated for 3.12 and replaced with importlib. Thank you very much for all the help!
