### ISSUE TITLE
i can't finish Step 6 according to "Install-Cadnano-Windows-v3.pdf"

### ISSUE THREAD

**Issue by MrZIer** [douglaslab/cadnano2#53]
i met the problem:
main.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources  # part of setuptools
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from . import cadnano
ImportError: cannot import name 'cadnano' from '__main__' (main.py)

**Comment by mwluqman** [comment]
I have problem with step 6 as well. 
I dont see the main.py
![Cadnano](https://github.com/douglaslab/cadnano2/assets/162850269/d15946a9-52f9-4428-a802-6e7b9f3f3963)

**Comment by zhangchangtian** [comment]
![image](https://github.com/user-attachments/assets/49c60855-5914-4fe0-a232-ef3626db64ed)
this is my problem

**Comment by sdouglas** [comment]
The tutorial is out of date. Please see the README file for the latest installation and running instructions.
