### ISSUE TITLE
can't open file

### ISSUE THREAD

**Issue by seohyun-123123** [douglaslab/cadnano2#54]
Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\Users\kwons\OneDrive\document\cadnano2>python main.py
python: can't open file 'C:\\Users\\kwons\\OneDrive\\document\\cadnano2\\main.py': [Errno 2] No such file or directory

C:\Users\kwons\OneDrive\document\cadnano2>

**Comment by sdouglas** [comment]
https://github.com/douglaslab/cadnano2#running
