### ISSUE TITLE
caDNAno2 mac frequently crashes

### ISSUE THREAD

**Issue by sdey15** [douglaslab/cadnano2#6]
The mac version crashes frequently - every 5mins or so. The python just crashes. How to solve this?

**Comment by gwynethchu** [comment]
I do have the same question! For small structure design everything works well, when it comes to a bigger one it would crash ONLY. Looks like I am not the only one.

**Comment by tinyolive** [comment]
Same thing is happening to me too, not sure how to resolve this.

**Comment by sdouglas** [comment]
Hi all, sorry for the inconvenience and slow response. 

Although we did not make any substantial changes to the cadnano2 source code in recent years, we have observed increasing instability with each new operating system release, and especially when new hardware (i.e., M1 macs) is released. These updates break (or degrade) compatibility with various libraries that we rely on, such as Qt and PyQt. This is a difficult and expensive issue, and very frustrating for us as well, as we are trying to provide useful and stable scientific tools as a service to the community.

Recently, I invested a few weeks' effort to port cadnano2 from PyQt5 to PyQt6. I would have liked to do this earlier, but it took about a year before PyQt6 was easy to install on M1 macs. Fortunately, the [recent release](https://github.com/douglaslab/cadnano2/releases) seems more stable on all macs that we've tested. There are still some lingering bugs, so please submit them along with the terminal output when you encounter issues. Thanks!
