### ISSUE TITLE
caDNAno2 frequently crashing due to EXC_BAD_ACCESS error

### ISSUE THREAD

**Issue by osleland** [douglaslab/cadnano2#7]
Process:               Python [33798]
Path:                  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.7.7 (3.7.7)
Code Type:             X86-64 (Native)
Parent Process:        zsh [33731]
Responsible:           Terminal [27213]
User ID:               501

Date/Time:             2020-06-19 09:02:23.121 -0400
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Bridge OS Version:     4.5 (17P5300)
Anonymous UUID:        4D04EE7F-6A6A-48B2-65C1-BE46576CBEFA

Sleep/Wake UUID:       E571E43E-D6BC-45A3-AF97-0F54708095C8

Time Awake Since Boot: 69000 seconds
Time Since Wake:       5600 seconds

**System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [33798]**

I tried uninstalling and reinstalling everything as well. My .bash_profile is identical to what is listed on the site. The application will launch and run for maybe a few minutes and then crash.

**Comment by sdouglas** [comment]
I suspect some dependency, such as PyQt 5.10, is not forward compatible with the latest versions of macOS. It may be a while before we have time to look into it so I suggest 1) using the legacy version of cadnano or, if you have programming experience, 2) trying to update to a newer version of PyQt5 in a separate virtual environment and see if that helps. We previously had some problems with anything after 5.10 so that’s why we fixed on that release, but maybe those are fixed now.

**Comment by osleland** [comment]
Update: I will still occasionally get some crashes, but they were significantly reduced when I started clearing app cache on my computer using MacKeeper. Now I try to keep 1-3 GB of RAM open while I use caDNAno2. I usually get exc_bad_access kern_invalid_address crashes now – next time it crashes I'll paste the error here.

**Comment by osleland** [comment]
Process:               Python [54901]
Path:                  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.7.7 (3.7.7)
Code Type:             X86-64 (Native)
Parent Process:        zsh [54818]
Responsible:           Terminal [54816]
User ID:               501

Date/Time:             2020-07-22 19:28:14.712 -0400
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Bridge OS Version:     4.5 (17P5300)
Anonymous UUID:        4D04EE7F-6A6A-48B2-65C1-BE46576CBEFA


Time Awake Since Boot: 3800 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

**Comment by sdouglas** [comment]
Please try the latest release, which has been ported to PyQt6. Follow the updated installation instructions in the [README](https://github.com/douglaslab/cadnano2/blob/master/README.md) and let me know if you have any issues.
