### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "windows" in "".

### ISSUE THREAD

**Issue by zhangshuwen967** [douglaslab/cadnano2#8]
When open the cadnano2 after installed. It showed below. Where is wrong. Thankyou.
D:\Users\淑文\Documents\GitHub\cadnano2>python main.py
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.

**Comment by sdouglas** [comment]
We recommend using pip to install the latest release, which has been ported to PyQt6.
